appname = openvpn
httpport = 8080
runmode = dev

sessionon = true

db_user = root
db_pass = 
db_host = 127.0.0.1
db_port = 3306
db_name = test
db_max_idle_conn = 30
db_max_open_conn = 200

username=admin
password=admin

expired_year=1
expired_month=0
expired_day=0

gt_uid=3
log_path= /etc/openvpn/openvpn-status.log